[build]
  command = "npm run build"  # Specify your build command
  publish = "dist"          # Specify the directory to deploy

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
